#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

# Commands
$application->add(new MakeTemplateCommand());
$application->add(new MakePartialCommand());
$application->add(new ThemeNameCommand());
$application->add(new ThemeDescriptionCommand());
$application->add(new ThemeVersionCommand());

$application->run();